name = "socialloop-zendesk-health-cron"
main = "index.js"
compatibility_date = "2026-06-27"
workers_dev = true

[triggers]
crons = ["0 * * * *"]

[secrets]
required = ["PAGES_BASE_URL", "ZENDESK_SYNC_SECRET"]

[observability]
enabled = true
