import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'

test('Activity Log is admin-only, read-only, filtered, and paginated', async () => {
  const page = await fs.readFile('activity-log.html', 'utf8')
  const script = await fs.readFile('scripts/activity-log.js', 'utf8')
  const migration = await fs.readFile('supabase/migrations/20260813120000_activity_log_read_model.sql', 'utf8')

  assert.match(page, /Activity Log/)
  assert.match(page, /activityCategory/)
  assert.match(page, /activityFrom/)
  assert.match(page, /activityTo/)
  assert.match(page, /activityPagination/)
  assert.match(script, /access\.is_admin/)
  assert.match(script, /activity_log_list/)
  assert.match(script, /p_limit: PAGE_SIZE/)
  assert.match(script, /p_offset: page \* PAGE_SIZE/)
  assert.match(script, /function statement\(/)
  assert.match(script, /display_details = statement/)
  assert.match(script, /row\.display_details/)
  assert.match(script, /Billed Clock-in/)
  assert.match(script, /was set to/)
  assert.match(script, /<details><summary>Technical details/)
  assert.match(script, /JSON\.stringify\(row\.technical_details/)
  assert.match(script, /attendance_deleted/)
  assert.match(script, /deleted an attendance record for/)
  assert.match(script, /Payroll period \$\{row\.details\.after\.period_label\} was recalculated/)
  assert.match(script, /updated \$\{possessive\(target\)\} schedule/)
  assert.match(script, /was changed from/)
  assert.match(script, /Clock-out/)
  assert.match(script, /row\.done_by \|\| 'System'/)
  assert.match(migration, /System Admin/)
  assert.doesNotMatch(script, /row\.details\.action|row\.technical_details\.action[^\n]*<td>/)
  assert.match(migration, /workforce_is_admin\(\)/)
  assert.match(migration, /actor\.is_system_admin then 'System Admin'/)
  assert.match(migration, /grant execute on function public\.activity_log_list/) 
  assert.match(migration, /payroll_audit_logs/)
  assert.match(migration, /workforce_audit_logs/)
})
